allowBuilds:
  "@parcel/watcher": true
  "@swc/core": true
  sharp: true
  unrs-resolver: true

minimumReleaseAge: 10080

trustPolicy:
  no-downgrade: true

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
