import { FavoritePairItem } from "./types";

export const MOCK_FAVORITE_PAIRS: FavoritePairItem[] = [
  {
    id: "USD-EUR",
    fromCode: "USD",
    toCode: "EUR",
    rate: 0.853,
    changePercent: 0.16,
    isFavorite: true,
  },
  {
    id: "GBP-USD",
    fromCode: "GBP",
    toCode: "USD",
    rate: 1.3575,
    changePercent: -0.22,
    isFavorite: true,
  },
  {
    id: "USD-JPY",
    fromCode: "USD",
    toCode: "JPY",
    rate: 157.91,
    changePercent: 0.04,
    isFavorite: true,
  },
  {
    id: "USD-BDT",
    fromCode: "USD",
    toCode: "BDT",
    rate: 122.92,
    changePercent: 0.18,
    isFavorite: true,
  },
  {
    id: "EUR-GBP",
    fromCode: "EUR",
    toCode: "GBP",
    rate: 0.8633,
    changePercent: 0.11,
    isFavorite: true,
  },
  {
    id: "AUD-NZD",
    fromCode: "AUD",
    toCode: "NZD",
    rate: 1.2217,
    changePercent: 0.23,
    isFavorite: true,
  },
  {
    id: "USD-INR",
    fromCode: "USD",
    toCode: "INR",
    rate: 94.91,
    changePercent: 0.05,
    isFavorite: true,
  },
  {
    id: "EUR-CHF",
    fromCode: "EUR",
    toCode: "CHF",
    rate: 1.0668,
    changePercent: -0.15,
    isFavorite: true,
  },
  {
    id: "GBP-JPY",
    fromCode: "GBP",
    toCode: "JPY",
    rate: 213.21,
    changePercent: 0.13,
    isFavorite: true,
  },
  {
    id: "USD-TRY",
    fromCode: "USD",
    toCode: "TRY",
    rate: 38.642,
    changePercent: 0.54,
    isFavorite: true,
  },
];
